# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
    - image: 'circleci/buildpack-deps:stretch'
    environment:
      IMAGE_NAME: docker-goof
      SNYK_TOKEN: cd6790c4-ed37-4fde-a9bb-9190b8e4539e
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: 'docker build -t $IMAGE_NAME:test .'
          name: Build Docker image
      - snyk/scan:
          docker-image-name: '$IMAGE_NAME:test'
          fail-on-issues: false
          monitor-on-build: true
          project: '${docker-goof}/${circleci-project-setup}-container'
          severity-threshold: high
          target-file: Dockerfile
          token-variable: SNYK_TOKEN
workflows: null